# Generated by Django 6.1 on 2026-09-02 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bloodrequests', '0001_initial'),
        ('donors', '0001_initial'),
        ('receivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='receivers.receiver'),
        ),
        migrations.AddField(
            model_name='donationrecord',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='donors.donor'),
        ),
        migrations.AddField(
            model_name='donationrecord',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_records', to='bloodrequests.bloodrequest'),
        ),
    ]
