# Generated by Django 6.0.3 on 2026-09-24 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodrequests', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='hospital_name_snapshot',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
